// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "MemoryHierarchy.h"
#include <protocol/TBinaryProtocol.h>
#include <server/TSimpleServer.h>
#include <transport/TServerSocket.h>
#include <transport/TTransportUtils.h>

using namespace facebook::thrift;
using namespace facebook::thrift::protocol;
using namespace facebook::thrift::transport;
using namespace facebook::thrift::server;

using boost::shared_ptr;

using namespace simple;

class MemoryHierarchyHandler : virtual public MemoryHierarchyIf {
 public:
  MemoryHierarchyHandler() {
    // Your initialization goes here
  }

  void step() {
    // Your implementation goes here
    printf("step\n");
  }

  void operate(const Work& w) {
    // Your implementation goes here
    printf("operate\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<MemoryHierarchyHandler> handler(new MemoryHierarchyHandler());
  shared_ptr<TProcessor> processor(new MemoryHierarchyProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

