/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "simple_constants.h"

namespace simple {

const simpleConstants g_simple_constants;

simpleConstants::simpleConstants() {
}

} // namespace

