/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef simple_CONSTANTS_H
#define simple_CONSTANTS_H

#include "simple_types.h"

namespace simple {

class simpleConstants {
 public:
  simpleConstants();

};

extern const simpleConstants g_simple_constants;

} // namespace

#endif
