/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package simple;


public class MemOp {
  public static final int LOAD = 1;
  public static final int STORE = 2;
  public static final int ABORT = 10;
  public static final int BEGIN = 11;
  public static final int COMMIT = 12;
  public static final int DISABLE = 13;
  public static final int ENABLE = 14;
  public static final int INFO = 15;
}
